"""UserBioTranslation model — C-3 multi-language-story.

Per-locale storage of artist bio translations.
LLM auto-translated (is_machine_translated=True) or manually edited (False).
Composite PK: (user_id, locale).
"""
from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, ForeignKey, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base

SUPPORTED_LOCALES = frozenset({"ko", "en", "ja", "zh", "es"})


class UserBioTranslation(Base):
    """Locale-specific artist bio translation.

    Primary key is composite (user_id, locale) — only one row per artist per locale.
    is_machine_translated=True  → generated by LLM Gateway
    is_machine_translated=False → manually edited by the artist
    """

    __tablename__ = "user_bio_translations"

    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        primary_key=True,
        nullable=False,
    )
    locale: Mapped[str] = mapped_column(
        String(8), primary_key=True, nullable=False
    )  # ko | en | ja | zh | es

    bio: Mapped[str] = mapped_column(Text, nullable=False)
    is_machine_translated: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=True, server_default="true"
    )
    # Updated on every save (manual or LLM)
    last_edited_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )
    # Set only when LLM Gateway was used for translation
    last_translated_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
